spring:
  profiles:
    active: dev

server:
  port: 8081

kraken:
  futures:
    rest-url: https://futures.kraken.com/derivatives/api/v3
    ws-url: wss://futures.kraken.com/ws/v1
    demo-rest-url: https://demo-futures.kraken.com/derivatives/api/v3
    demo-ws-url: wss://demo-futures.kraken.com/ws/v1
    use-demo: false
    api-key: ${KRAKEN_API_KEY}
    api-secret: ${KRAKEN_API_SECRET}
    demo-api-key: ${KRAKEN_DEMO_API_KEY:}
    demo-api-secret: ${KRAKEN_DEMO_API_SECRET:}
